[package]
name = "impression"
version = "3.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gettext-rs = { version = "0.7.0", features = ["gettext-system"] }
glib = "0.18.0"
gtk = { version = "0.7.0", package = "gtk4", features = ["blueprint", "v4_10"] }
gtk-macros = { version = "0.7.0", package = "gtk4-macros" }
adw = { version = "0.5.0", package = "libadwaita", features = ["v1_4"] }
log = "0.4.17"
once_cell = "1.17.1"
pretty_env_logger = "0.5.0"
itertools = "0.11.0"
futures = "0.3.28"
ashpd = "0.4.0"
dbus-udisks2 = { version = "0.3" }
dbus = "0.9.7"
libc = "0.2.144"
async-std = "1.12.0"
srmw = "0.1.1"
reqwest = { version = "0.11", features = ["blocking", "stream"] }
regex = "1.9.1"
roxmltree = "0.18.0"
chrono = "0.4.26"
anyhow = "1.0.75"
thiserror = "1.0.49"
derivative = "2.2.0"
tokio = "1.33.0"
